### PR TITLE
Require gnu-efi 3.0.18 or later

### PR DESCRIPTION
**Pull request by superm1**
Closes: https://github.com/fwupd/fwupd/issues/7010

### CODE REVIEW

**Comment by superm1** [comment]
Is the pkgconfig missing from the devel package maybe?

**Comment by hughsie** [comment]
> rpm -qlp gnu-efi-devel-3.0.18-1.fc40.x86_64.rpm

I see:

	..
	/usr/lib/libefi.a
	/usr/lib/libgnuefi.a
	/usr/lib/pkgconfig/gnu-efi.pc
	/usr/share/doc/gnu-efi-devel
	..

Ahh. Maybe usr/lib/pkgconfig vs usr/lib64/pkgconfig perhaps?

**Comment by superm1** [comment]
> Ahh. Maybe usr/lib/pkgconfig vs usr/lib64/pkgconfig perhaps?

Yeah something is up with how that devel package is built.  I don't think it's correct.

**Comment by hughsie** [comment]
Fixing now, give me 20 mins...

**Review by hughsie — APPROVED** [review]

**Comment by hughsie** [comment]
> Is a cross compile hard in Fedora

I don't think we cross build it; it's native on aarch64, no?

**Comment by superm1** [comment]
> > Is a cross compile hard in Fedora
> 
> I don't think we cross build it; it's native on aarch64, no?

Right but I'm wondering if we can cross build it for CI?

**Comment by superm1** [comment]
We don't need to get it in to tag, but we should keep an issue open to have some CI task for building all the other architectures either with qemu static or cross compile.

I don't care if it's Debian or Fedora, but we shouldn't be surprised in the future ideally.

**Pull request merged**
