### PR TITLE
Small meson improvements

### PR DESCRIPTION
**Pull request by rossburton**

### CODE REVIEW

**Review by superm1 — COMMENTED** [review]
I seem to recall this was because of cross compiling

**Comment by superm1** [comment]
> I seem to recall this was because of cross compiling

So I guess with making this change a meson cross file would be needed. Which is probably the right direction though.

**Comment by rossburton** [comment]
People doing cross with Meson already have a cross file configured, fwupd-efi is special and doesn't respect it.

objcopy is easy, ld and gcc are "a bit" harder.

**Review by superm1 — APPROVED** [review]
LGTM then.

**Review by hughsie — APPROVED** [review]
TBH, you and Ross knows what you're doing with this than I do.

**Pull request merged**
