### PR TITLE
Revert "lds: add init_array/fini_array sections"

### PR DESCRIPTION
**Pull request by hughsie**
This reverts commit 855511c894bd9e37e26ba2979eedfc095b11764a.

### CODE REVIEW

**Comment by hughsie** [comment]
@gmbr3 this is needed to unbreak capsule updates on Fedora (with our ancient gnu-efi) -- is that expected?

**Comment by gmbr3** [comment]
> @gmbr3 this is needed to unbreak capsule updates on Fedora (with our ancient gnu-efi) -- is that expected?

Very much not - I suspect Fedora is still missing some of my post patches on @vathpela original constructor work
Likely alignment etc.

Could you post the readelf -a output of fwup.so and the build log

**Comment by hughsie** [comment]
>  I suspect Fedora is still missing some of my post patches

Fedora has a big mess to unwind! I've posted some more of our patches to the upstream list, as I'm trying to get the delta compared to upstream to zero.

The logs from our super-old version are https://koji.fedoraproject.org/koji/buildinfo?buildID=2422342 and attached
[readelf.txt](https://github.com/fwupd/fwupd-efi/files/14638162/readelf.txt)
.

**Comment by gmbr3** [comment]
```
 0x0000000000000002 (PLTRELSZ)           3720 (bytes)
 0x0000000000000017 (JMPREL)             0x11000
 0x0000000000000007 (RELA)               0x11000
```
.rela.plt is merged into .rela (I reverted in main) as proven causes the size to be incorrect and ld can't figure out the obvious, it should be 24 not 3720

```
4: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 _fini_array
7: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 _init_array_end
10: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 __CTOR_END__
12: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 _fini_array_end
14: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 __DTOR_END__
20: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 _init_array
23: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 __DTOR_LIST__
32: 000000000000fd10     0 NOTYPE  GLOBAL DEFAULT    7 __CTOR_LIST__
```
Old naming scheme - likely _entry can't find it's old names as my linker script change has the new names
And this usually triggers a warning when the symbols are missed but it's not in the build log??

**Comment by hughsie** [comment]
Perhaps as predicted, using gnu-efi from git master this revert is not required -- and the firmware update is deployed correctly. I'll continue the Fedora rebase -- and with those patches I sent upstream I think I can drop *all* the downstream patches.

**Comment by superm1** [comment]
It sounds like we have an implicit dependency now on a particular gnu-efi version that we didn't previously have? Can we express that?

**Comment by gmbr3** [comment]
> It sounds like we have an implicit dependency now on a particular gnu-efi version that we didn't previously have? Can we express that?

Probably once Richard has ported Fedora, it's still 3.0.15+ as set by NX stack but Fedora been hanging on very patched version of 3.0.11

**Comment by gmbr3** [comment]
> I was hoping for a clean 3.0.18 tarball in the not so distant future.

Same although it's been so long I'm pushing the very unhappily named 3.0.17+53 to openSUSE

**Pull request closed without merging**
